### ISSUE TITLE
Missing opencv requirement

### ISSUE THREAD

**Issue by folkien** [wojtke/music-video-automaker#1]
Missing opencv in reqs.

```python
python merge_testing.py film.mp4 music.mp3 -o output.mp4 --threshold 2      Traceback (most recent call last):
  File "/home/spasz/Dokumenty/AISP/music-video-automaker/env3.8/lib/python3.8/site-packages/scenedetect/__init__.py", line 28, in <module>
    import cv2 as _
ModuleNotFoundError: No module named 'cv2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "merge_testing.py", line 3, in <module>
    from scene_detect import get_scene_list
  File "/home/spasz/Dokumenty/AISP/music-video-automaker/scene_detect.py", line 1, in <module>
    from scenedetect import VideoManager
  File "/home/spasz/Dokumenty/AISP/music-video-automaker/env3.8/lib/python3.8/site-packages/scenedetect/__init__.py", line 30, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: OpenCV could not be found, try installing opencv-python:

pip install opencv-python

```

**Comment by wojtke** [comment]
requirements.txt updated
